# brew install postgres
# initdb /usr/local/var/postgres -E utf8
# pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start

# This is how you create databases:

# createuser -s andnow
# createdb andnow_development
# createdb andnow_test

development:
  adapter: postgresql
  database: andnow_development
  user: andnow
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: andnow_test
  user: andnow
  host: localhost
  pool: 5
  timeout: 5000
